spring:
  datasource:
    url: jdbc:mysql://localhost/products
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: products
  activemq:
    broker-url: tcp://localhost:60000
    user: admin
    password: password
    packages:
      trusted: fr.ippon
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: '*'


