spring:
  datasource:
    url: jdbc:mysql://localhost/products
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: products
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: password
    packages:
      trusted: fr.ippon
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'


