version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ducks'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./sql/create-database.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
      # - ./sql/create-database.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      internal-epitech:
        ipv4_address: ${IP_MYSQL}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  eureka:
    image: ducks/infra-eureka:latest
    ports:
      - ${porteureka}:8761
    environment:
      - eureka.client.healthcheck.enabled=true
      - eureka_client_serviceUrl_defaultZone=http://${IP_EUREKA}:8761/eureka/
    healthcheck:
      test: curl -f http://localhost:8761/ || exit 1
      timeout: 5s
      interval: 5s
      retries: 15
    networks:
      internal-epitech:
        ipv4_address: ${IP_EUREKA}
  msproducts:
    image: ducks/products:${VERSION_PRODUCTS}
    environment:
      - eureka_client_serviceUrl_defaultZone=http://${IP_EUREKA}:8761/eureka/
      - spring.datasource.url=jdbc:mysql://${IP_MYSQL}/products
      - spring.activemq.broker-url=tcp://${IP_ACTIVE}:61616
    depends_on:
      eureka:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      internal-epitech:
        ipv4_address: ${IP_MSPRODUCTS}
  ms-orders:
    image: ducks/orders:${VERSION_ORDERS}
    environment:
      - eureka_client_serviceUrl_defaultZone=http://${IP_EUREKA}:8761/eureka/
      - spring.datasource.url=jdbc:mysql://${IP_MYSQL}/products
      - spring.activemq.broker-url=tcp://${IP_ACTIVE}:61616
    depends_on:
      eureka:
        condition: service_healthy
    networks:
      internal-epitech:
        ipv4_address: ${IP_ORDERS}
  zuul:
    image: ducks/infra-gateway:lastest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://${IP_EUREKA}:8761/eureka/
    ports:
      - ${portgateway}:8762
    depends_on:
      eureka:
        condition: service_healthy
    networks:
      internal-epitech:
        ipv4_address: ${IP_ZUUL}
  messagebroker:
    image: rmohr/activemq:5.10.0
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
    ports:
      - ${activeMqbroker}:61616
      - ${activeMqweb}:8161
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 200MB
    networks:
      internal-epitech:
        ipv4_address: ${IP_ACTIVE}
volumes:
  db_data:
    name: db-data
networks:
  internal-epitech:
    driver: bridge
    name: internal-epitech-${ENV}
    ipam:
      driver: default
      config:
        - subnet: ${networkSubnet}
