INSERT INTO ducks_products values (1,'petit','jaune',10)
INSERT INTO ducks_products values (2,'petit','vert',3)
INSERT INTO ducks_products values (3,'petit','bleu',5)
INSERT INTO ducks_products values (4,'grand','jaune',6)
INSERT INTO ducks_products values (5,'grand','vert',8)
INSERT INTO ducks_products values (6,'grand','bleu',9)
