spring:
  datasource:
    url: jdbc:mysql://localhost/orders
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orders
  activemq:
    broker-url: tcp://localhost:60000
    user: admin
    password: password
    packages:
      trusted: fr.ippon

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

