spring:
  datasource:
    url: jdbc:mysql://localhost/orders
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orders
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: password
    packages:
      trusted: fr.ippon
  eureka:
    instance:
      preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'


